'use client'

import Link from 'next/link'
import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { AlertCircle, ArrowRight, CheckCircle2, Clock, Loader2, MapPin, MessageSquareWarning, User, XCircle } from 'lucide-react'

type Appeal = { id: string; reason: string; details: string | null; status: string; decisionNotes: string | null; createdAt: string; reviewedAt: string | null; citizen: { id: string; fullName: string; nationalId: string; phone: string; gov: string | null; center: string | null }; application: { id: string; trackingNumber: string; status: string; stage: string; submittedAt: string; land: { gov: string | null; center: string | null; village: string | null; detail: string | null; totalFaddan: number; authorityName: string | null } | null }; reviewedBy: { id: string; fullName: string } | null }
const STATUS_LABELS: Record<string, string> = { PENDING: 'قيد المراجعة', APPROVED: 'مقبول', REJECTED: 'مرفوض' }

export default function AppealDetailPage() {
  const params = useParams<{ id: string }>()
  const router = useRouter()
  const id = params.id
  const [appeal, setAppeal] = useState<Appeal | null>(null)
  const [loading, setLoading] = useState(true)
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState('')
  const [success, setSuccess] = useState('')
  const [showReviewModal, setShowReviewModal] = useState(false)
  const [decision, setDecision] = useState<'APPROVED' | 'REJECTED' | null>(null)
  const [notes, setNotes] = useState('')
  const load = async () => { setLoading(true); try { const res = await fetch(`/api/staff/appeals/${id}`); if (!res.ok) { if (res.status === 404) router.push('/portal/appeals'); return }; setAppeal((await res.json()).appeal) } finally { setLoading(false) } }
  useEffect(() => { if (id) void load(); /* eslint-disable-next-line react-hooks/exhaustive-deps */ }, [id])
  const submitReview = async () => { if (!decision) return; setSubmitting(true); setError(''); try { const res = await fetch(`/api/staff/appeals/${id}/review`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ decision, notes: notes || undefined }) }); const data = await res.json(); if (!res.ok) { setError(data.error || 'فشل الحفظ'); return }; setSuccess(decision === 'APPROVED' ? 'تم قبول التظلم' : 'تم رفض التظلم'); setShowReviewModal(false); setDecision(null); setNotes(''); await load() } catch { setError('تعذّر الاتصال') } finally { setSubmitting(false) } }
  if (loading) return <div className="flex justify-center py-32"><Loader2 className="w-6 h-6 animate-spin text-[#0d7a3e]" /></div>
  if (!appeal) return null
  const isPending = appeal.status === 'PENDING'
  return <div className="space-y-6">
    <Link href="/portal/appeals" className="inline-flex items-center gap-2 text-[13px] font-bold text-black/60 hover:text-black"><ArrowRight className="w-4 h-4" />رجوع للتظلمات</Link>
    {error && <div className="rounded-xl bg-red-50 border border-red-200 text-red-700 text-[13px] font-semibold p-3 flex items-center justify-between"><span><AlertCircle className="w-4 h-4 inline me-1" />{error}</span><button onClick={() => setError('')} className="font-bold">×</button></div>}
    {success && <div className="rounded-xl bg-green-50 border border-green-200 text-green-700 text-[13px] font-semibold p-3 flex items-center justify-between"><span><CheckCircle2 className="w-4 h-4 inline me-1" />{success}</span><button onClick={() => setSuccess('')} className="font-bold">×</button></div>}
    <div className="rounded-[20px] bg-gradient-to-l from-[#c89a2c] to-[#a87f1e] text-white p-6"><div className="text-[11px] opacity-85">تظلم على طلب رقم</div><div className="mt-1 font-mono text-[20px] font-extrabold" dir="ltr">{appeal.application.trackingNumber}</div><span className="inline-block mt-3 px-3 py-1 rounded-full bg-white/20 text-[11px] font-bold">{STATUS_LABELS[appeal.status] || appeal.status}</span><div className="mt-3 text-[11px] opacity-85">تاريخ التقديم: {new Date(appeal.createdAt).toLocaleDateString('ar-EG')}</div></div>
    <div className="grid lg:grid-cols-[1.3fr_0.7fr] gap-6"><div className="space-y-6">
      <div className="rounded-[18px] bg-white border border-black/5 p-5"><h3 className="font-extrabold text-[14px] flex items-center gap-2 mb-4"><MessageSquareWarning className="w-4 h-4 text-[#c89a2c]" />محتوى التظلم</h3><div className="rounded-xl bg-[#fbfaf2] border border-[#c89a2c]/20 p-3"><div className="text-[10px] text-black/50 font-bold mb-1">سبب التظلم</div><div className="text-[13px] font-bold leading-7">{appeal.reason}</div></div>{appeal.details && <div className="mt-3 rounded-xl bg-[#f9fbf9] border border-black/5 p-3"><div className="text-[10px] text-black/50 font-bold mb-1">تفاصيل إضافية</div><div className="text-[12px] leading-7 whitespace-pre-line">{appeal.details}</div></div>}</div>
      <div className="rounded-[18px] bg-white border border-black/5 p-5"><h3 className="font-extrabold text-[14px] flex items-center gap-2 mb-4"><User className="w-4 h-4 text-[#0d7a3e]" />بيانات المواطن</h3><div className="grid md:grid-cols-2 gap-4 text-[12px]"><Info label="الاسم" value={appeal.citizen.fullName} /><Info label="الرقم القومي" value={appeal.citizen.nationalId} /><Info label="الهاتف" value={appeal.citizen.phone} /><Info label="المحافظة" value={appeal.citizen.gov || '—'} /></div></div>
      <div className="rounded-[18px] bg-white border border-black/5 p-5"><h3 className="font-extrabold text-[14px] flex items-center gap-2 mb-4"><MapPin className="w-4 h-4 text-[#0d7a3e]" />بيانات الأرض</h3>{appeal.application.land ? <div className="grid md:grid-cols-2 gap-4 text-[12px]"><Info label="المحافظة" value={appeal.application.land.gov || '—'} /><Info label="المركز" value={appeal.application.land.center || '—'} /><Info label="القرية" value={appeal.application.land.village || '—'} /><Info label="جهة الولاية" value={appeal.application.land.authorityName || '—'} /><Info label="المساحة" value={`${appeal.application.land.totalFaddan.toFixed(4)} فدان`} /><Info label="وصف الموقع" value={appeal.application.land.detail || '—'} /></div> : <div className="text-center text-[12px] text-black/50 py-4">لا توجد بيانات</div>}</div>
    </div><div className="space-y-4">
      {isPending ? <div className="rounded-[18px] bg-white border-2 border-[#c89a2c] p-5"><h3 className="font-extrabold text-[14px] flex items-center gap-2 mb-3"><Clock className="w-4 h-4 text-[#c89a2c]" />اتخاذ القرار</h3><p className="text-[11px] text-black/55 leading-6 mb-4">راجع محتوى التظلم والبيانات، ثم اختر القرار المناسب.</p><div className="space-y-2"><button onClick={() => { setDecision('APPROVED'); setShowReviewModal(true) }} className="w-full h-11 rounded-full bg-[#0d7a3e] text-white font-bold text-[13px] flex items-center justify-center gap-2"><CheckCircle2 className="w-4 h-4" />قبول التظلم</button><button onClick={() => { setDecision('REJECTED'); setShowReviewModal(true) }} className="w-full h-11 rounded-full bg-red-500 text-white font-bold text-[13px] flex items-center justify-center gap-2"><XCircle className="w-4 h-4" />رفض التظلم</button></div></div> : <div className={`rounded-[18px] bg-white border-2 p-5 ${appeal.status === 'APPROVED' ? 'border-green-500' : 'border-red-500'}`}><h3 className="font-extrabold text-[14px] mb-3">القرار</h3><div className="font-bold">{appeal.status === 'APPROVED' ? 'تم القبول' : 'تم الرفض'}</div>{appeal.reviewedBy && <div className="mt-4 text-[11px] text-black/60">المراجع: <strong>{appeal.reviewedBy.fullName}</strong></div>}{appeal.decisionNotes && <div className="mt-4 rounded-xl bg-[#f9fbf9] p-3 text-[12px]">{appeal.decisionNotes}</div>}</div>}
      <Link href={`/portal/applications/${appeal.application.id}`} className="rounded-[18px] bg-white border border-black/5 p-4 flex items-center justify-between"><div><div className="text-[12px] font-bold">عرض الطلب الأصلي</div><div className="text-[10px] text-black/50">{appeal.application.trackingNumber}</div></div><ArrowRight className="w-4 h-4 rotate-180" /></Link>
    </div></div>
    {showReviewModal && decision && <div className="fixed inset-0 z-50 bg-black/50 flex items-center justify-center p-4"><div className="bg-white rounded-[20px] w-full max-w-md p-5"><h3 className="font-extrabold text-[16px] mb-4">{decision === 'APPROVED' ? 'تأكيد قبول التظلم' : 'تأكيد رفض التظلم'}</h3><textarea value={notes} onChange={(e) => setNotes(e.target.value)} className="input mb-4" placeholder="ملاحظات المراجع (اختياري)" rows={4} maxLength={1000} /><div className="flex gap-3"><button onClick={() => { setShowReviewModal(false); setDecision(null); setNotes('') }} className="flex-1 h-11 rounded-full border border-black/10 font-bold">إلغاء</button><button onClick={() => void submitReview()} disabled={submitting} className={`flex-1 h-11 rounded-full text-white font-bold disabled:opacity-50 ${decision === 'APPROVED' ? 'bg-[#0d7a3e]' : 'bg-red-500'}`}>{submitting ? <Loader2 className="w-4 h-4 animate-spin mx-auto" /> : 'تأكيد'}</button></div></div></div>}
  </div>
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-[#f9fbf9] border border-black/5 p-3"><div className="text-[10px] text-black/50 font-bold">{label}</div><div className="mt-1 text-[12px] font-bold">{value}</div></div> }
